
-- RESPALDO DE BASE DE DATOS (FILE)
DECLARE @bd VARCHAR(255)
DECLARE @archivo VARCHAR(255)
DECLARE @fecha VARCHAR(255)
                            
SET @bd='IEEPOSYNC' 
SET @fecha = convert(varchar, getdate(), 112)
SET @archivo = '\\172.16.3.34\E$\'+@bd+'_backup_'+ @fecha +'.bak'
 
BACKUP DATABASE [IEEPOREPLICA] TO DISK = @archivo
WITH NOFORMAT, NOINIT, NAME = 'IEEPOReplica Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
 
 -- Transaction Log Full Due to ‘CHECKPOINT’

 ALTER DATABASE IEEPOSYNC  set  EMERGENCY 
ALTER DATABASE IEEPOSYNC  REBUILD LOG ON (NAME='IEEPO_LOG',FILENAME='G:\IEEPOREPLICA_log.ldf')
ALTER DATABASE IEEPOSYNC  set ONLINE
ALTER DATABASE IEEPOSYNC  SET MULTI_USER 